height: 500
width: 500
crops_per_image: 100
# height:
#   desc: Supposed to be the average of the height of a character of a dataset
#   value: 500
# width:
#   desc: Supposed to be the average of the height of a character of a dataset
#   value: 500